Repository slcommunity/511, pull requests merged in 2021-12, with the labels that each got.

#42 Feature/newpost
  src/main/java/com/example/tilproject/controller/NewPostController.java
  src/main/java/com/example/tilproject/domain/NewPost.java
  src/main/java/com/example/tilproject/dto/SearchRequestDto.java
  src/main/java/com/example/tilproject/dto/SearchResponse.java
  src/main/java/com/example/tilproject/repository/adminRepository/NewPostRepository.java
  src/main/java/com/example/tilproject/service/NewpostService.java
  src/main/java/com/example/tilproject/utils/CrawlingScheduler.java
  src/main/resources/application.yml
  src/main/resources/static/css/newpost.css
  src/main/resources/static/js/newpost.js
  src/main/resources/static/newpost.html
Labels: Feature/Function, Status:Done, Proirity:Critical

#44 Feature/timeattack
  src/main/java/com/example/tilproject/TilProjectApplication.java
  src/main/java/com/example/tilproject/controller/JwtAuthenticationFilter.java
  src/main/java/com/example/tilproject/controller/admin/AdminTurnController.java
  src/main/java/com/example/tilproject/controller/admin/AdminUrlController.java
  src/main/java/com/example/tilproject/controller/admin/AdminUserController.java
  src/main/java/com/example/tilproject/domain/Turn.java
  src/main/java/com/example/tilproject/service/adminService/AdminTurnService.java
  src/main/java/com/example/tilproject/service/adminService/AdminUrlService.java
  src/main/java/com/example/tilproject/service/adminService/AdminUserService.java
  src/main/resources/application.yml
  src/main/resources/static/admin.html
  src/main/resources/static/css/urlCollection.css
  src/main/resources/static/header.html
  src/main/resources/static/index.html
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/urlCollection.js
  src/main/resources/static/urlcollection.html
Labels: Feature/Function, Status:Reviewing, Priority:High

#53 Board/#33
  src/main/java/com/example/tilproject/controller/BoardController.java
  src/main/java/com/example/tilproject/controller/CommentController.java
  src/main/java/com/example/tilproject/domain/Board.java
  src/main/java/com/example/tilproject/domain/Comment.java
  src/main/java/com/example/tilproject/dto/BoardCommentRequestDto.java
  src/main/java/com/example/tilproject/dto/BoardRequestDto.java
  src/main/java/com/example/tilproject/dto/NewCommentRequestDto.java
  src/main/java/com/example/tilproject/repository/BoardRepository.java
  src/main/java/com/example/tilproject/repository/CommentRepository.java
  src/main/java/com/example/tilproject/service/BoardService.java
  src/main/java/com/example/tilproject/service/CommentService.java
  src/main/java/com/example/tilproject/service/NewpostService.java
  src/main/resources/application.yml
  src/main/resources/static/boardEdit.html
  src/main/resources/static/boardList.html
  src/main/resources/static/boardView.html
  src/main/resources/static/boardWrite.html
  src/main/resources/static/css/boardEdit.css
  src/main/resources/static/css/boardList.css
  src/main/resources/static/css/boardView.css
  src/main/resources/static/css/boardWrite.css
  src/main/resources/static/header.html
  src/main/resources/static/js/boardEdit.js
  src/main/resources/static/js/boardList.js
  src/main/resources/static/js/boardView.js
  src/main/resources/static/js/boardWrite.js
  src/main/resources/static/js/login.js
Labels: Status:Done

#54 Feature/my board fix
  src/main/java/com/example/tilproject/domain/Board.java
  src/main/resources/static/boardEdit.html
  src/main/resources/static/boardList.html
  src/main/resources/static/boardView.html
  src/main/resources/static/boardWrite.html
  src/main/resources/static/header.html
  src/main/resources/static/index.html
  src/main/resources/static/js/boardEdit.js
  src/main/resources/static/js/boardList.js
  src/main/resources/static/js/boardView.js
  src/main/resources/static/js/boardWrite.js
  src/main/resources/static/js/myBoard.js
  src/main/resources/static/js/myComment.js
  src/main/resources/static/myBoard.html
  src/main/resources/static/myComment.html
Labels: Feature/Document, Bugfix/Function

#55 Feature/validate delete
  src/main/java/com/example/tilproject/controller/BoardController.java
  src/main/java/com/example/tilproject/controller/CommentController.java
  src/main/java/com/example/tilproject/service/BoardService.java
  src/main/java/com/example/tilproject/service/CommentService.java
  src/main/resources/static/boardEdit.html
  src/main/resources/static/header.html
  src/main/resources/static/js/boardEdit.js
  src/main/resources/static/js/boardView.js
  src/main/resources/static/js/myBoard.js
  src/main/resources/static/js/myComment.js
Labels: Feature/Document

#58 footer 수정
  src/main/resources/application.yml
  src/main/resources/static/footer.html
Labels: Status:Done

#60 [update] 댓글 항목 추가 -[#59]
  src/main/java/com/example/tilproject/controller/CommentController.java
  src/main/java/com/example/tilproject/dto/CommentResponseDto.java
  src/main/java/com/example/tilproject/service/CommentService.java
  src/main/resources/static/boardView.html
  src/main/resources/static/css/boardView.css
  src/main/resources/static/js/boardView.js
Labels: Feature/Document

#61 [update] 비로그인 사용자 자유게시판 처리 -[#57]
  src/main/resources/static/boardList.html
  src/main/resources/static/js/boardEdit.js
  src/main/resources/static/js/boardList.js
  src/main/resources/static/js/boardView.js
  src/main/resources/static/js/boardWrite.js
Labels: Bugfix/Function

#64 Feature/swag
  build.gradle
  src/main/java/com/example/tilproject/config/SwaggerConfig.java
  src/main/java/com/example/tilproject/controller/BoardController.java
  src/main/java/com/example/tilproject/controller/CommentController.java
  src/main/java/com/example/tilproject/controller/MemberController.java
  src/main/java/com/example/tilproject/controller/NewPostController.java
  src/main/java/com/example/tilproject/controller/RoleController.java
  src/main/java/com/example/tilproject/controller/UserApiController.java
  src/main/java/com/example/tilproject/controller/admin/AdminTurnController.java
  src/main/java/com/example/tilproject/controller/admin/AdminUrlController.java
  src/main/java/com/example/tilproject/controller/admin/AdminUserController.java
  src/main/java/com/example/tilproject/utils/CrawlingScheduler.java
  src/main/resources/static/index.html
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/boardEdit.js
  src/main/resources/static/js/boardList.js
  src/main/resources/static/js/boardView.js
  src/main/resources/static/js/boardWrite.js
  src/main/resources/static/js/login.js
  src/main/resources/static/js/myBoard.js
  src/main/resources/static/js/myComment.js
  src/main/resources/static/js/newpost.js
  src/main/resources/static/js/urlCollection.js
  src/main/resources/static/js/userInfo.js
  src/main/resources/static/memberCard.html
  src/main/resources/static/userinfo.html
Labels: Feature/Document, Status:Done
