Repository slcommunity/511, pull requests merged in 2021-11, with the labels that each got.

#20 Feature/login
  build.gradle
  src/main/java/com/example/tilproject/TilProjectApplication.java
  src/main/java/com/example/tilproject/config/AmazonS3Config.java
  src/main/java/com/example/tilproject/controller/FrontController.java
  src/main/java/com/example/tilproject/controller/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/tilproject/controller/JwtAuthenticationFilter.java
  src/main/java/com/example/tilproject/controller/UserApiController.java
  src/main/java/com/example/tilproject/domain/User.java
  src/main/java/com/example/tilproject/dto/JwtResponse.java
  src/main/java/com/example/tilproject/dto/SignupRequestDto.java
  src/main/java/com/example/tilproject/dto/UserDto.java
  src/main/java/com/example/tilproject/repository/UserRepository.java
  src/main/java/com/example/tilproject/security/UserDetailsImpl.java
  src/main/java/com/example/tilproject/security/UserDetailsServiceImpl.java
  src/main/java/com/example/tilproject/security/WebSecurityConfig.java
  src/main/java/com/example/tilproject/service/UserService.java
  src/main/java/com/example/tilproject/utils/JwtTokenUtil.java
  src/main/java/com/example/tilproject/utils/S3Uploader.java
  src/main/resources/application.yml
  src/main/resources/static/css/login.css
  src/main/resources/static/image/default-image.jpg
  src/main/resources/static/index.html
  src/main/resources/static/js/index.js
  src/main/resources/static/js/login.js
  src/main/resources/static/js/logout.js
  src/main/resources/static/js/userInfo.js
  src/main/resources/static/login.html
  src/main/resources/static/userinfo.html
Labels: Status:Reviewing

#26 [fix]기수입력 오류 해결, 정보수정 placeholer->value
  src/main/java/com/example/tilproject/domain/Board.java
  src/main/resources/static/index.html
  src/main/resources/static/js/login.js
  src/main/resources/static/memberCard.html
  src/main/resources/static/userinfo.html
Labels: Bugfix/Function

#27 Feature/admin
  src/main/java/com/example/tilproject/controller/admin/AdminTurnController.java
  src/main/java/com/example/tilproject/controller/admin/AdminUrlController.java
  src/main/java/com/example/tilproject/controller/admin/AdminUserController.java
  src/main/java/com/example/tilproject/domain/Board.java
  src/main/java/com/example/tilproject/domain/NewPost.java
  src/main/java/com/example/tilproject/domain/Review.java
  src/main/java/com/example/tilproject/domain/Turn.java
  src/main/java/com/example/tilproject/domain/Url.java
  src/main/java/com/example/tilproject/domain/UrlSection.java
  src/main/java/com/example/tilproject/domain/User.java
  src/main/java/com/example/tilproject/domain/UserStatus.java
  src/main/java/com/example/tilproject/dto/TurnDto.java
  src/main/java/com/example/tilproject/dto/TurnModifyDto.java
  src/main/java/com/example/tilproject/dto/TurnRequestDto.java
  src/main/java/com/example/tilproject/dto/UrlCreateDeleteDto.java
  src/main/java/com/example/tilproject/dto/UrlModifyDto.java
  src/main/java/com/example/tilproject/dto/UrlTurnDto.java
  src/main/java/com/example/tilproject/dto/UserGetDto.java
  src/main/java/com/example/tilproject/dto/UserPagingRequestDto.java
  src/main/java/com/example/tilproject/repository/adminRepository/TurnRepository.java
  src/main/java/com/example/tilproject/repository/adminRepository/UrlRepository.java
  src/main/java/com/example/tilproject/repository/adminRepository/UserRepository.java
  src/main/java/com/example/tilproject/service/adminService/AdminTurnService.java
  src/main/java/com/example/tilproject/service/adminService/AdminUrlService.java
  src/main/java/com/example/tilproject/service/adminService/AdminUserService.java
  src/main/java/com/example/tilproject/utils/PagingResult.java
  src/main/java/com/example/tilproject/utils/Result.java
  src/main/resources/static/admin.html
  src/main/resources/static/js/admin.js
Labels: Status:Done
